<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model\Install;
use Carbon\Carbon;

class VineyardVarietiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Create on: 28-09-2015
     *
     * @return void
     */
    public function run()
    {
        DB::table('crop_varieties')->insert([
            ['crop_id' => 1, 'crop_variety_name' => 'Airén', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Alarije', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Albariño', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Albillo', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Albillo Mayor', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Albillo Real', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Alcañón', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Baladí Verdejo', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Bastardo Blanco', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Bermejuela', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Breval', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Borba', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Burrablanca', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Cayetana Blanca', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Chardonnay', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Chenin', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Chelva/Montua', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Cigüente', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Colombard', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Dona Blanca', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Dorarilla', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Eva/Beba de los Santos', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Folle Blanche', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Forastera Blanca', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Garnacha Blanca', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Garrido Fino', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Gewürztraminer', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Giró Ros', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Gros Manseng', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Godello', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Gual', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Lado', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Lairén', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Loureira', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Listán', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Listán blanco de Canarias', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Macabeo', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Malbec', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Malvar', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Malvasía', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],  
            ['crop_id' => 1, 'crop_variety_name' => 'Malvasía Aromática', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Malvasia Blanca', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Malvasía Castellana', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Malvasía de Sitges', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Malvasía Volcánica', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Merseguera', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Moscatel de Alejandría', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Moscatel de grano menudo o Morisca', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Ondarrabi Zuri', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Palomino', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Palomino Fino', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Parellada/Montonenc/Montonega', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Pardillo', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Pardina', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Pedro Ximénez', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Perruno', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Petit Manseng', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Petit Courbu', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Picapoll Blanco', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Planta Fina de Pedralba', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Planta Nova', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Riesling', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Sabro', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Sauvignon Blanc/Blanco', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Semillón Blanc', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Subirat Parent', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Tardana/Planta Nova', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Treixadura', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Tortosí', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Torrontés', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Turruntés', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Verdello', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Verdejo', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Verdil', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Vijiriego', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Vinyater', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Viognier', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Viura', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Xarelo/Xarello', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Zalema', 'crop_variety_type' => 1, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Bastardo Negro', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Bobal', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Bonicaire', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Brancellao', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Bruñal (Albarín Tinto)', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Cabernet Franc', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Cabernet Sauvignon', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Caíño Bravo', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Caíño Longo', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Caíño Tinto', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Callet', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Cariñena (Mazuela)', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Carrasquín', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Castañal', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Castellana Negra', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Espadeiro', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Ferrón', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Fogoneu', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Forcallat Tinta', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Frasco', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Garnacha Gris', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Garnacha Peluda', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Garnacha Roja', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Garnacha Tinta', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Garnacha Tintorera', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Gorgollassa', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Graciano', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Gran Negro', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Jaen Tinto', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Juan García', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Juan Ibáñez', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Listán Negro', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Listán Prieto', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Malvasía Rosada', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Manto Negro', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Maturana Tinta', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Mazuela', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Mencía', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Merenzao', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Merlot', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Monastrell', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Moravia Agria', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Moravia Dulce', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Moristel', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Moscatel Negro', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Mouratón', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Negramoll', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Ondarrabi Beltza', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Parraleta', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Pedral', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Petit Verdot', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Picapoll Negro', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Pinot Noir', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Prieto Picudo', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Rojal Tinta', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Romé', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Ruby Cabernet', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Rufete', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Samsó', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Sousón', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Sumoll Tinto', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Syrah', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Tempranillo', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Tinta del País', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Tintilla', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Tintilla de Rota', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Tinto Fino', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Trepat', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Vidadillo', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Vijariego Negro', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['crop_id' => 1, 'crop_variety_name' => 'Marselan', 'crop_variety_type' => 2, 'created_at' => new DateTime, 'updated_at' => new DateTime],
        ]);
    }
}
