<?php

return [
    'admin'             => 'bullseye',
    'agenda'            => 'book',
    'agronomic'         => 'lemon',
    'alert'             => 'exclamation-circle',
    'arrow-left'        => 'chevron-circle-left',
    'arrow-right'       => 'chevron-circle-right',
    'assign'            => 'arrow-circle-right',
    'bars'              => 'bars',
    'building'          => 'university',
    'bus'               => 'bus',
    'calendar'          => 'calendar-times',
    'car'               => 'car',
    'cancel'            => 'ban',
    'change'            => 'retweet',
    'clients'           => 'handshake',
    'company'           => 'briefcase',
    'config'            => 'cogs',
    'date'              => 'calendar',
    'delete'            => 'trash',
    'download'          => 'download',
    'edaphology'        => 'tags',
    'edit'              => 'edit',
    'email'             => 'envelope-open',
    'error'             => 'exclamation-triangle',
    'euro'              => 'eur',
    'excel'             => 'table',
    'exit'              => 'window-close',
    'file'              => 'file-text',
    'form'              => 'check-square',
    'framework'         => 'align-justify',
    'graph'             => 'chart-line',
    'hashtag'           => 'hashtag',
    'id'                => 'id-card',
    'image'             => 'images',
    'info'              => 'info-circle',
    'invoice'           => 'file-text',
    'link'              => 'external-link-alt',
    'list'              => 'list-alt',
    'login'             => 'sign-in-alt',
    'map'               => 'map-marker',
    'mark'              => 'thumbtack',
    'minus'             => 'minus',
    'new'               => 'plus-circle',
    'note'              => 'sticky-note',
    'password'          => 'unlock-alt',
    'percent'           => 'percent',
    'profile'           => 'cog',
    'question'          => 'question-circle',
    'reset'             => 'undo',
    'refresh'           => 'sync',
    'roles'             => 'lock',
    'search'            => 'search',
    'select'            => 'check-square',
    'social'            => 'facebook-square',
    'submit'            => 'share-square',
    'success'           => 'thumbs-up',
    'suitcase'          => 'suitcase',
    'table'             => 'table',
    'time'              => 'clock',
    'telephone'         => 'phone-square',
    'print'             => 'print',
    'pointer'           => 'hand-pointer',
    'upload'            => 'upload',
    'user'              => 'user-circle',
    'user-alt'          => 'user',
    'users'             => 'users',
    'world'             => 'globe',
    'wrench'            => 'wrench',

    //Specials
    'check'             => 'check-square',
    'uncheck'           => 'square',

    //Sidebar menu for admin
    //The routes must be like: clients, crops,....
    //Name-key came from Resources/Lang/i18n/Navbar/Administration
    'administration::clients'           => 'users',
    'administration::crops'             => 'fab:envira',
    'administration::irrigations'       => 'tint',
    'administration::trainings'         => 'map-signs',
    'administration::configs'           => 'cogs',
    'administration::biocides'          => 'flask',
    'administration::climatic_stations' => 'info-circle',
    'administration::climatics'         => 'sun',
    'administration::countries'         => 'globe',
    'administration::errors'            => 'exclamation-triangle',
    'administration::modules'           => 'fab:modx',
    'administration::options'           => 'check-square',

    //Sections
    'crop'              => 'pagelines',
    'pest'              => 'bug',
    'plot'              => 'buromobelexperte',
    'tree'              => 'tree',
    'variety'           => 'sitemap',
    'weather'           => 'snowflake',

];
