<?php

use Illuminate\Database\Seeder;

class RegionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('regions')->delete();
        
        \DB::table('regions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'country_id' => 1,
                'state_id' => 16,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Álava',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'country_id' => 1,
                'state_id' => 8,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Albacete',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'country_id' => 1,
                'state_id' => 10,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Alicante',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'country_id' => 1,
                'state_id' => 1,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Almería',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'country_id' => 1,
                'state_id' => 7,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Ávila',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'country_id' => 1,
                'state_id' => 11,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Badajoz',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'country_id' => 1,
                'state_id' => 4,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Illes Balears',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'country_id' => 1,
                'state_id' => 9,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Barcelona',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'country_id' => 1,
                'state_id' => 7,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Burgos',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'country_id' => 1,
                'state_id' => 11,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Cáceres',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'country_id' => 1,
                'state_id' => 1,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Cádiz',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'country_id' => 1,
                'state_id' => 10,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Castellón',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'country_id' => 1,
                'state_id' => 8,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Ciudad Real',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'country_id' => 1,
                'state_id' => 1,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Córdoba',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'country_id' => 1,
                'state_id' => 12,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'A Coruña',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'country_id' => 1,
                'state_id' => 8,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Cuenca',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'country_id' => 1,
                'state_id' => 9,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Girona',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'country_id' => 1,
                'state_id' => 1,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Granada',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'country_id' => 1,
                'state_id' => 8,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Guadalajara',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'country_id' => 1,
                'state_id' => 16,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Guipúzcoa',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'country_id' => 1,
                'state_id' => 1,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Huelva',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'country_id' => 1,
                'state_id' => 2,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Huesca',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'country_id' => 1,
                'state_id' => 1,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Jaén',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'country_id' => 1,
                'state_id' => 7,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'León',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'country_id' => 1,
                'state_id' => 9,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Lleida',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'country_id' => 1,
                'state_id' => 17,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'La Rioja',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'country_id' => 1,
                'state_id' => 12,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Lugo',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'country_id' => 1,
                'state_id' => 13,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Madrid',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'country_id' => 1,
                'state_id' => 1,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Málaga',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'country_id' => 1,
                'state_id' => 14,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Murcia',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'country_id' => 1,
                'state_id' => 15,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Navarra',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'country_id' => 1,
                'state_id' => 12,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Ourense',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'country_id' => 1,
                'state_id' => 3,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Asturias',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'country_id' => 1,
                'state_id' => 7,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Palencia',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'country_id' => 1,
                'state_id' => 5,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Las Palmas',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'country_id' => 1,
                'state_id' => 12,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Pontevedra',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'country_id' => 1,
                'state_id' => 7,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Salamanca',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'country_id' => 1,
                'state_id' => 5,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Santa Cruz de Tenerife',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'country_id' => 1,
                'state_id' => 6,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Cantabria',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'country_id' => 1,
                'state_id' => 7,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Segovia',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'country_id' => 1,
                'state_id' => 1,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Sevilla',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'country_id' => 1,
                'state_id' => 7,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Soria',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'country_id' => 1,
                'state_id' => 9,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Tarragona',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'country_id' => 1,
                'state_id' => 2,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Teruel',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'country_id' => 1,
                'state_id' => 8,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Toledo',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'country_id' => 1,
                'state_id' => 10,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Valencia',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'country_id' => 1,
                'state_id' => 7,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Valladolid',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'country_id' => 1,
                'state_id' => 16,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Vizcaya',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'country_id' => 1,
                'state_id' => 7,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Zamora',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'country_id' => 1,
                'state_id' => 2,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Zaragoza',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'country_id' => 1,
                'state_id' => 18,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Ceuta',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'country_id' => 1,
                'state_id' => 19,
                'region_lat' => '0.000000',
                'region_lng' => '0.000000',
                'region_name' => 'Melilla',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}